'use client';
//
// ------------------------------------------------------------------
//
// @env        NOT APPLICABLE
// @file       REQUIRED - This file is required for the app to run.
// @reference  REQUIRED - This file is referenced by other files.
// @generator  REQUIRED - This file is generated by the agent.
//
// ------------------------------------------------------------------
//
// This file is required for the app to run. It contains the
// Firebase client provider that ensures Firebase is initialized
// only once on the client.
//
// ------------------------------------------------------------------

import { useEffect, useState } from 'react';
import { initializeFirebase, FirebaseProvider } from '@/firebase';
import type { FirebaseApp } from 'firebase/app';
import type { Auth } from 'firebase/auth';
import type { Firestore } from 'firebase/firestore';

type FirebaseServices = {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
};

// NOTE: This provider is no longer used as we switched to localStorage.
// It is kept for potential future re-integration with Firebase.
export function FirebaseClientProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [firebase, setFirebase] = useState<FirebaseServices | null>(null);

  useEffect(() => {
    // const services = initializeFirebase();
    // setFirebase(services);
  }, []);

  if (firebase) {
    return (
      <FirebaseProvider
        app={firebase.app}
        auth={firebase.auth}
        firestore={firebase.firestore}
      >
        {children}
      </FirebaseProvider>
    );
  }

  return <>{children}</>;
}
