//
// ------------------------------------------------------------------
//
// @env        REQUIRED - Value is provided by the user.
// @file       REQUIRED - This file is required for the app to run.
// @reference  REQUIRED - This file is referenced by other files.
// @generator  REQUIRED - This file is generated by the agent.
//
// ------------------------------------------------------------------
//
// This file is required for the app to run. It contains the
// Firebase configuration object. This file is referenced by
// other files in the app.
//
// ------------------------------------------------------------------

export const firebaseConfig = {
  apiKey: "AIzaSyAwnbnm4Ppx_W13HD-2oovstyXsOvCLUqI",
  authDomain: "studio-6824616472-f4d1a.firebaseapp.com",
  projectId: "studio-6824616472-f4d1a",
  storageBucket: "studio-6824616472-f4d1a.firebasestorage.app",
  messagingSenderId: "100829848894",
  appId: "1:100829848894:web:97f8e8e08da480be80786f"
};
