'use client';
//
// ------------------------------------------------------------------
//
// @env        NOT APPLICABLE
// @file       REQUIRED - This file is required for the app to run.
// @reference  REQUIRED - This file is referenced by other files.
// @generator  REQUIRED - This- file is generated by the agent.
//
// ------------------------------------------------------------------
//
// This file is required for the app to run. It serves as a barrel
// file for Firebase functionality. It exports the initializeFirebase
// function and all the provider hooks.
//
// ------------------------------------------------------------------

import { initializeApp, getApps, getApp, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';
import { firebaseConfig } from './config';

export function initializeFirebase(): {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
} {
  const app = getApps().length > 0 ? getApp() : initializeApp(firebaseConfig);
  const auth = getAuth(app);
  const firestore = getFirestore(app);

  return { app, auth, firestore };
}

export * from './provider';
export * from './client-provider';
