'use client';
//
// ------------------------------------------------------------------
//
// @env        NOT APPLICABLE
// @file       REQUIRED - This file is required for the app to run.
// @reference  REQUIRED - This file is referenced by other files.
// @generator  REQUIRED - This file is generated by the agent.
//
// ------------------------------------------------------------------
//
// This file is required for the app to run. It contains the
// Firebase provider and hooks to access Firebase services.
//
// ------------------------------------------------------------------

import { createContext, useContext } from 'react';
import type { FirebaseApp } from 'firebase/app';
import type { Auth } from 'firebase/auth';
import type { Firestore } from 'firebase/firestore';

type FirebaseContextValue = {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
};

const FirebaseContext = createContext<FirebaseContextValue | null>(null);

export const FirebaseProvider = ({
  children,
  ...value
}: {
  children: React.ReactNode;
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
}) => {
  return (
    <FirebaseContext.Provider value={value}>{children}</FirebaseContext.Provider>
  );
};

export const useFirebase = () => {
  const context = useContext(FirebaseContext);
  if (!context) {
    throw new Error('useFirebase must be used within a FirebaseProvider');
  }
  return context;
};

export const useFirebaseApp = () => useFirebase().app;
export const useAuth = () => useFirebase().auth;
export const useFirestore = () => useFirebase().firestore;
